# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aaron/projects/Infinity-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aaron/projects/Infinity-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/aaron/projects/Infinity-master/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/projects/Infinity-master/CMakeFiles /home/aaron/projects/Infinity-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/projects/Infinity-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin2cpp

# Build rule for target.
bin2cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin2cpp
.PHONY : bin2cpp

# fast build rule for target.
bin2cpp/fast:
	$(MAKE) -f tools/CMakeFiles/bin2cpp.dir/build.make tools/CMakeFiles/bin2cpp.dir/build
.PHONY : bin2cpp/fast

#=============================================================================
# Target rules for targets named hashgen

# Build rule for target.
hashgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hashgen
.PHONY : hashgen

# fast build rule for target.
hashgen/fast:
	$(MAKE) -f tools/CMakeFiles/hashgen.dir/build.make tools/CMakeFiles/hashgen.dir/build
.PHONY : hashgen/fast

#=============================================================================
# Target rules for targets named psppack

# Build rule for target.
psppack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psppack
.PHONY : psppack

# fast build rule for target.
psppack/fast:
	$(MAKE) -f tools/CMakeFiles/psppack.dir/build.make tools/CMakeFiles/psppack.dir/build
.PHONY : psppack/fast

#=============================================================================
# Target rules for targets named pack_user_fw_module

# Build rule for target.
pack_user_fw_module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pack_user_fw_module
.PHONY : pack_user_fw_module

# fast build rule for target.
pack_user_fw_module/fast:
	$(MAKE) -f tools/CMakeFiles/pack_user_fw_module.dir/build.make tools/CMakeFiles/pack_user_fw_module.dir/build
.PHONY : pack_user_fw_module/fast

#=============================================================================
# Target rules for targets named pack_kernel_module

# Build rule for target.
pack_kernel_module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pack_kernel_module
.PHONY : pack_kernel_module

# fast build rule for target.
pack_kernel_module/fast:
	$(MAKE) -f tools/CMakeFiles/pack_kernel_module.dir/build.make tools/CMakeFiles/pack_kernel_module.dir/build
.PHONY : pack_kernel_module/fast

#=============================================================================
# Target rules for targets named pack_updater

# Build rule for target.
pack_updater: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pack_updater
.PHONY : pack_updater

# fast build rule for target.
pack_updater/fast:
	$(MAKE) -f tools/CMakeFiles/pack_updater.dir/build.make tools/CMakeFiles/pack_updater.dir/build
.PHONY : pack_updater/fast

#=============================================================================
# Target rules for targets named power

# Build rule for target.
power: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 power
.PHONY : power

# fast build rule for target.
power/fast:
	$(MAKE) -f stubs/power/CMakeFiles/power.dir/build.make stubs/power/CMakeFiles/power.dir/build
.PHONY : power/fast

#=============================================================================
# Target rules for targets named scePower_0002

# Build rule for target.
scePower_0002: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scePower_0002
.PHONY : scePower_0002

# fast build rule for target.
scePower_0002/fast:
	$(MAKE) -f stubs/power/CMakeFiles/scePower_0002.dir/build.make stubs/power/CMakeFiles/scePower_0002.dir/build
.PHONY : scePower_0002/fast

#=============================================================================
# Target rules for targets named scePower_0001

# Build rule for target.
scePower_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scePower_0001
.PHONY : scePower_0001

# fast build rule for target.
scePower_0001/fast:
	$(MAKE) -f stubs/power/CMakeFiles/scePower_0001.dir/build.make stubs/power/CMakeFiles/scePower_0001.dir/build
.PHONY : scePower_0001/fast

#=============================================================================
# Target rules for targets named scePower_0000

# Build rule for target.
scePower_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scePower_0000
.PHONY : scePower_0000

# fast build rule for target.
scePower_0000/fast:
	$(MAKE) -f stubs/power/CMakeFiles/scePower_0000.dir/build.make stubs/power/CMakeFiles/scePower_0000.dir/build
.PHONY : scePower_0000/fast

#=============================================================================
# Target rules for targets named syscon

# Build rule for target.
syscon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syscon
.PHONY : syscon

# fast build rule for target.
syscon/fast:
	$(MAKE) -f stubs/syscon/CMakeFiles/syscon.dir/build.make stubs/syscon/CMakeFiles/syscon.dir/build
.PHONY : syscon/fast

#=============================================================================
# Target rules for targets named sceSyscon_driver_0001

# Build rule for target.
sceSyscon_driver_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceSyscon_driver_0001
.PHONY : sceSyscon_driver_0001

# fast build rule for target.
sceSyscon_driver_0001/fast:
	$(MAKE) -f stubs/syscon/CMakeFiles/sceSyscon_driver_0001.dir/build.make stubs/syscon/CMakeFiles/sceSyscon_driver_0001.dir/build
.PHONY : sceSyscon_driver_0001/fast

#=============================================================================
# Target rules for targets named sceSyscon_driver_0000

# Build rule for target.
sceSyscon_driver_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceSyscon_driver_0000
.PHONY : sceSyscon_driver_0000

# fast build rule for target.
sceSyscon_driver_0000/fast:
	$(MAKE) -f stubs/syscon/CMakeFiles/sceSyscon_driver_0000.dir/build.make stubs/syscon/CMakeFiles/sceSyscon_driver_0000.dir/build
.PHONY : sceSyscon_driver_0000/fast

#=============================================================================
# Target rules for targets named vshbridge

# Build rule for target.
vshbridge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vshbridge
.PHONY : vshbridge

# fast build rule for target.
vshbridge/fast:
	$(MAKE) -f stubs/vshbridge/CMakeFiles/vshbridge.dir/build.make stubs/vshbridge/CMakeFiles/vshbridge.dir/build
.PHONY : vshbridge/fast

#=============================================================================
# Target rules for targets named sceVshBridge_0001

# Build rule for target.
sceVshBridge_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceVshBridge_0001
.PHONY : sceVshBridge_0001

# fast build rule for target.
sceVshBridge_0001/fast:
	$(MAKE) -f stubs/vshbridge/CMakeFiles/sceVshBridge_0001.dir/build.make stubs/vshbridge/CMakeFiles/sceVshBridge_0001.dir/build
.PHONY : sceVshBridge_0001/fast

#=============================================================================
# Target rules for targets named sceVshBridge_0000

# Build rule for target.
sceVshBridge_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceVshBridge_0000
.PHONY : sceVshBridge_0000

# fast build rule for target.
sceVshBridge_0000/fast:
	$(MAKE) -f stubs/vshbridge/CMakeFiles/sceVshBridge_0000.dir/build.make stubs/vshbridge/CMakeFiles/sceVshBridge_0000.dir/build
.PHONY : sceVshBridge_0000/fast

#=============================================================================
# Target rules for targets named netifhandle

# Build rule for target.
netifhandle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 netifhandle
.PHONY : netifhandle

# fast build rule for target.
netifhandle/fast:
	$(MAKE) -f stubs/netifhandle/CMakeFiles/netifhandle.dir/build.make stubs/netifhandle/CMakeFiles/netifhandle.dir/build
.PHONY : netifhandle/fast

#=============================================================================
# Target rules for targets named sceNetIfhandle_lib_0001

# Build rule for target.
sceNetIfhandle_lib_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceNetIfhandle_lib_0001
.PHONY : sceNetIfhandle_lib_0001

# fast build rule for target.
sceNetIfhandle_lib_0001/fast:
	$(MAKE) -f stubs/netifhandle/CMakeFiles/sceNetIfhandle_lib_0001.dir/build.make stubs/netifhandle/CMakeFiles/sceNetIfhandle_lib_0001.dir/build
.PHONY : sceNetIfhandle_lib_0001/fast

#=============================================================================
# Target rules for targets named sceNetIfhandle_lib_0000

# Build rule for target.
sceNetIfhandle_lib_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceNetIfhandle_lib_0000
.PHONY : sceNetIfhandle_lib_0000

# fast build rule for target.
sceNetIfhandle_lib_0000/fast:
	$(MAKE) -f stubs/netifhandle/CMakeFiles/sceNetIfhandle_lib_0000.dir/build.make stubs/netifhandle/CMakeFiles/sceNetIfhandle_lib_0000.dir/build
.PHONY : sceNetIfhandle_lib_0000/fast

#=============================================================================
# Target rules for targets named memlmd

# Build rule for target.
memlmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memlmd
.PHONY : memlmd

# fast build rule for target.
memlmd/fast:
	$(MAKE) -f stubs/memlmd/CMakeFiles/memlmd.dir/build.make stubs/memlmd/CMakeFiles/memlmd.dir/build
.PHONY : memlmd/fast

#=============================================================================
# Target rules for targets named semaphore_0001

# Build rule for target.
semaphore_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semaphore_0001
.PHONY : semaphore_0001

# fast build rule for target.
semaphore_0001/fast:
	$(MAKE) -f stubs/memlmd/CMakeFiles/semaphore_0001.dir/build.make stubs/memlmd/CMakeFiles/semaphore_0001.dir/build
.PHONY : semaphore_0001/fast

#=============================================================================
# Target rules for targets named semaphore_0000

# Build rule for target.
semaphore_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semaphore_0000
.PHONY : semaphore_0000

# fast build rule for target.
semaphore_0000/fast:
	$(MAKE) -f stubs/memlmd/CMakeFiles/semaphore_0000.dir/build.make stubs/memlmd/CMakeFiles/semaphore_0000.dir/build
.PHONY : semaphore_0000/fast

#=============================================================================
# Target rules for targets named modulemgr

# Build rule for target.
modulemgr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modulemgr
.PHONY : modulemgr

# fast build rule for target.
modulemgr/fast:
	$(MAKE) -f stubs/modulemgr/CMakeFiles/modulemgr.dir/build.make stubs/modulemgr/CMakeFiles/modulemgr.dir/build
.PHONY : modulemgr/fast

#=============================================================================
# Target rules for targets named ModuleMgrForUser_0001

# Build rule for target.
ModuleMgrForUser_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ModuleMgrForUser_0001
.PHONY : ModuleMgrForUser_0001

# fast build rule for target.
ModuleMgrForUser_0001/fast:
	$(MAKE) -f stubs/modulemgr/CMakeFiles/ModuleMgrForUser_0001.dir/build.make stubs/modulemgr/CMakeFiles/ModuleMgrForUser_0001.dir/build
.PHONY : ModuleMgrForUser_0001/fast

#=============================================================================
# Target rules for targets named ModuleMgrForUser_0000

# Build rule for target.
ModuleMgrForUser_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ModuleMgrForUser_0000
.PHONY : ModuleMgrForUser_0000

# fast build rule for target.
ModuleMgrForUser_0000/fast:
	$(MAKE) -f stubs/modulemgr/CMakeFiles/ModuleMgrForUser_0000.dir/build.make stubs/modulemgr/CMakeFiles/ModuleMgrForUser_0000.dir/build
.PHONY : ModuleMgrForUser_0000/fast

#=============================================================================
# Target rules for targets named kexploit

# Build rule for target.
kexploit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kexploit
.PHONY : kexploit

# fast build rule for target.
kexploit/fast:
	$(MAKE) -f kexploit/CMakeFiles/kexploit.dir/build.make kexploit/CMakeFiles/kexploit.dir/build
.PHONY : kexploit/fast

#=============================================================================
# Target rules for targets named kernel_helper

# Build rule for target.
kernel_helper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper
.PHONY : kernel_helper

# fast build rule for target.
kernel_helper/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper.dir/build.make kernel_helper/CMakeFiles/kernel_helper.dir/build
.PHONY : kernel_helper/fast

#=============================================================================
# Target rules for targets named kernel_helper_user_0000

# Build rule for target.
kernel_helper_user_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper_user_0000
.PHONY : kernel_helper_user_0000

# fast build rule for target.
kernel_helper_user_0000/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper_user_0000.dir/build.make kernel_helper/CMakeFiles/kernel_helper_user_0000.dir/build
.PHONY : kernel_helper_user_0000/fast

#=============================================================================
# Target rules for targets named kernel_helper_user

# Build rule for target.
kernel_helper_user: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper_user
.PHONY : kernel_helper_user

# fast build rule for target.
kernel_helper_user/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper_user.dir/build.make kernel_helper/CMakeFiles/kernel_helper_user.dir/build
.PHONY : kernel_helper_user/fast

#=============================================================================
# Target rules for targets named kernel_helper_user_0001

# Build rule for target.
kernel_helper_user_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper_user_0001
.PHONY : kernel_helper_user_0001

# fast build rule for target.
kernel_helper_user_0001/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper_user_0001.dir/build.make kernel_helper/CMakeFiles/kernel_helper_user_0001.dir/build
.PHONY : kernel_helper_user_0001/fast

#=============================================================================
# Target rules for targets named kernel_helper_user_0003

# Build rule for target.
kernel_helper_user_0003: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper_user_0003
.PHONY : kernel_helper_user_0003

# fast build rule for target.
kernel_helper_user_0003/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper_user_0003.dir/build.make kernel_helper/CMakeFiles/kernel_helper_user_0003.dir/build
.PHONY : kernel_helper_user_0003/fast

#=============================================================================
# Target rules for targets named kernel_helper_user_0002

# Build rule for target.
kernel_helper_user_0002: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper_user_0002
.PHONY : kernel_helper_user_0002

# fast build rule for target.
kernel_helper_user_0002/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper_user_0002.dir/build.make kernel_helper/CMakeFiles/kernel_helper_user_0002.dir/build
.PHONY : kernel_helper_user_0002/fast

#=============================================================================
# Target rules for targets named kernel_helper_user_0004

# Build rule for target.
kernel_helper_user_0004: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_helper_user_0004
.PHONY : kernel_helper_user_0004

# fast build rule for target.
kernel_helper_user_0004/fast:
	$(MAKE) -f kernel_helper/CMakeFiles/kernel_helper_user_0004.dir/build.make kernel_helper/CMakeFiles/kernel_helper_user_0004.dir/build
.PHONY : kernel_helper_user_0004/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0002

# Build rule for target.
libconfig_kernel_0002: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0002
.PHONY : libconfig_kernel_0002

# fast build rule for target.
libconfig_kernel_0002/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0002.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0002.dir/build
.PHONY : libconfig_kernel_0002/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0003

# Build rule for target.
libconfig_kernel_0003: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0003
.PHONY : libconfig_kernel_0003

# fast build rule for target.
libconfig_kernel_0003/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0003.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0003.dir/build
.PHONY : libconfig_kernel_0003/fast

#=============================================================================
# Target rules for targets named libconfig_user_0003

# Build rule for target.
libconfig_user_0003: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0003
.PHONY : libconfig_user_0003

# fast build rule for target.
libconfig_user_0003/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0003.dir/build.make libconfig/CMakeFiles/libconfig_user_0003.dir/build
.PHONY : libconfig_user_0003/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0007

# Build rule for target.
libconfig_kernel_0007: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0007
.PHONY : libconfig_kernel_0007

# fast build rule for target.
libconfig_kernel_0007/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0007.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0007.dir/build
.PHONY : libconfig_kernel_0007/fast

#=============================================================================
# Target rules for targets named libconfig

# Build rule for target.
libconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig
.PHONY : libconfig

# fast build rule for target.
libconfig/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig.dir/build.make libconfig/CMakeFiles/libconfig.dir/build
.PHONY : libconfig/fast

#=============================================================================
# Target rules for targets named libconfig_user_0000

# Build rule for target.
libconfig_user_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0000
.PHONY : libconfig_user_0000

# fast build rule for target.
libconfig_user_0000/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0000.dir/build.make libconfig/CMakeFiles/libconfig_user_0000.dir/build
.PHONY : libconfig_user_0000/fast

#=============================================================================
# Target rules for targets named libconfig_user_0004

# Build rule for target.
libconfig_user_0004: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0004
.PHONY : libconfig_user_0004

# fast build rule for target.
libconfig_user_0004/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0004.dir/build.make libconfig/CMakeFiles/libconfig_user_0004.dir/build
.PHONY : libconfig_user_0004/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0005

# Build rule for target.
libconfig_kernel_0005: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0005
.PHONY : libconfig_kernel_0005

# fast build rule for target.
libconfig_kernel_0005/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0005.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0005.dir/build
.PHONY : libconfig_kernel_0005/fast

#=============================================================================
# Target rules for targets named libconfig_user_0011

# Build rule for target.
libconfig_user_0011: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0011
.PHONY : libconfig_user_0011

# fast build rule for target.
libconfig_user_0011/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0011.dir/build.make libconfig/CMakeFiles/libconfig_user_0011.dir/build
.PHONY : libconfig_user_0011/fast

#=============================================================================
# Target rules for targets named libconfig_user_0012

# Build rule for target.
libconfig_user_0012: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0012
.PHONY : libconfig_user_0012

# fast build rule for target.
libconfig_user_0012/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0012.dir/build.make libconfig/CMakeFiles/libconfig_user_0012.dir/build
.PHONY : libconfig_user_0012/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0000

# Build rule for target.
libconfig_kernel_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0000
.PHONY : libconfig_kernel_0000

# fast build rule for target.
libconfig_kernel_0000/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0000.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0000.dir/build
.PHONY : libconfig_kernel_0000/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0009

# Build rule for target.
libconfig_kernel_0009: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0009
.PHONY : libconfig_kernel_0009

# fast build rule for target.
libconfig_kernel_0009/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0009.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0009.dir/build
.PHONY : libconfig_kernel_0009/fast

#=============================================================================
# Target rules for targets named libconfig_static

# Build rule for target.
libconfig_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_static
.PHONY : libconfig_static

# fast build rule for target.
libconfig_static/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_static.dir/build.make libconfig/CMakeFiles/libconfig_static.dir/build
.PHONY : libconfig_static/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0011

# Build rule for target.
libconfig_kernel_0011: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0011
.PHONY : libconfig_kernel_0011

# fast build rule for target.
libconfig_kernel_0011/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0011.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0011.dir/build
.PHONY : libconfig_kernel_0011/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0001

# Build rule for target.
libconfig_kernel_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0001
.PHONY : libconfig_kernel_0001

# fast build rule for target.
libconfig_kernel_0001/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0001.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0001.dir/build
.PHONY : libconfig_kernel_0001/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0012

# Build rule for target.
libconfig_kernel_0012: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0012
.PHONY : libconfig_kernel_0012

# fast build rule for target.
libconfig_kernel_0012/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0012.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0012.dir/build
.PHONY : libconfig_kernel_0012/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0006

# Build rule for target.
libconfig_kernel_0006: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0006
.PHONY : libconfig_kernel_0006

# fast build rule for target.
libconfig_kernel_0006/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0006.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0006.dir/build
.PHONY : libconfig_kernel_0006/fast

#=============================================================================
# Target rules for targets named libconfig_user_0001

# Build rule for target.
libconfig_user_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0001
.PHONY : libconfig_user_0001

# fast build rule for target.
libconfig_user_0001/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0001.dir/build.make libconfig/CMakeFiles/libconfig_user_0001.dir/build
.PHONY : libconfig_user_0001/fast

#=============================================================================
# Target rules for targets named libconfig_user_0005

# Build rule for target.
libconfig_user_0005: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0005
.PHONY : libconfig_user_0005

# fast build rule for target.
libconfig_user_0005/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0005.dir/build.make libconfig/CMakeFiles/libconfig_user_0005.dir/build
.PHONY : libconfig_user_0005/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0004

# Build rule for target.
libconfig_kernel_0004: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0004
.PHONY : libconfig_kernel_0004

# fast build rule for target.
libconfig_kernel_0004/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0004.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0004.dir/build
.PHONY : libconfig_kernel_0004/fast

#=============================================================================
# Target rules for targets named libconfig_user_0002

# Build rule for target.
libconfig_user_0002: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0002
.PHONY : libconfig_user_0002

# fast build rule for target.
libconfig_user_0002/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0002.dir/build.make libconfig/CMakeFiles/libconfig_user_0002.dir/build
.PHONY : libconfig_user_0002/fast

#=============================================================================
# Target rules for targets named libconfig_user_0007

# Build rule for target.
libconfig_user_0007: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0007
.PHONY : libconfig_user_0007

# fast build rule for target.
libconfig_user_0007/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0007.dir/build.make libconfig/CMakeFiles/libconfig_user_0007.dir/build
.PHONY : libconfig_user_0007/fast

#=============================================================================
# Target rules for targets named libconfig_user_0009

# Build rule for target.
libconfig_user_0009: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0009
.PHONY : libconfig_user_0009

# fast build rule for target.
libconfig_user_0009/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0009.dir/build.make libconfig/CMakeFiles/libconfig_user_0009.dir/build
.PHONY : libconfig_user_0009/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0008

# Build rule for target.
libconfig_kernel_0008: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0008
.PHONY : libconfig_kernel_0008

# fast build rule for target.
libconfig_kernel_0008/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0008.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0008.dir/build
.PHONY : libconfig_kernel_0008/fast

#=============================================================================
# Target rules for targets named libconfig_user_0008

# Build rule for target.
libconfig_user_0008: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0008
.PHONY : libconfig_user_0008

# fast build rule for target.
libconfig_user_0008/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0008.dir/build.make libconfig/CMakeFiles/libconfig_user_0008.dir/build
.PHONY : libconfig_user_0008/fast

#=============================================================================
# Target rules for targets named libconfig_kernel_0010

# Build rule for target.
libconfig_kernel_0010: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel_0010
.PHONY : libconfig_kernel_0010

# fast build rule for target.
libconfig_kernel_0010/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel_0010.dir/build.make libconfig/CMakeFiles/libconfig_kernel_0010.dir/build
.PHONY : libconfig_kernel_0010/fast

#=============================================================================
# Target rules for targets named libconfig_user_0006

# Build rule for target.
libconfig_user_0006: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0006
.PHONY : libconfig_user_0006

# fast build rule for target.
libconfig_user_0006/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0006.dir/build.make libconfig/CMakeFiles/libconfig_user_0006.dir/build
.PHONY : libconfig_user_0006/fast

#=============================================================================
# Target rules for targets named libconfig_user_0010

# Build rule for target.
libconfig_user_0010: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user_0010
.PHONY : libconfig_user_0010

# fast build rule for target.
libconfig_user_0010/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user_0010.dir/build.make libconfig/CMakeFiles/libconfig_user_0010.dir/build
.PHONY : libconfig_user_0010/fast

#=============================================================================
# Target rules for targets named libconfig_user

# Build rule for target.
libconfig_user: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_user
.PHONY : libconfig_user

# fast build rule for target.
libconfig_user/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_user.dir/build.make libconfig/CMakeFiles/libconfig_user.dir/build
.PHONY : libconfig_user/fast

#=============================================================================
# Target rules for targets named libconfig_kernel

# Build rule for target.
libconfig_kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libconfig_kernel
.PHONY : libconfig_kernel

# fast build rule for target.
libconfig_kernel/fast:
	$(MAKE) -f libconfig/CMakeFiles/libconfig_kernel.dir/build.make libconfig/CMakeFiles/libconfig_kernel.dir/build
.PHONY : libconfig_kernel/fast

#=============================================================================
# Target rules for targets named reboot

# Build rule for target.
reboot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reboot
.PHONY : reboot

# fast build rule for target.
reboot/fast:
	$(MAKE) -f firmware/reboot/CMakeFiles/reboot.dir/build.make firmware/reboot/CMakeFiles/reboot.dir/build
.PHONY : reboot/fast

#=============================================================================
# Target rules for targets named infinityboot

# Build rule for target.
infinityboot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infinityboot
.PHONY : infinityboot

# fast build rule for target.
infinityboot/fast:
	$(MAKE) -f firmware/infinityboot/CMakeFiles/infinityboot.dir/build.make firmware/infinityboot/CMakeFiles/infinityboot.dir/build
.PHONY : infinityboot/fast

#=============================================================================
# Target rules for targets named libinfinityUser_0000

# Build rule for target.
libinfinityUser_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityUser_0000
.PHONY : libinfinityUser_0000

# fast build rule for target.
libinfinityUser_0000/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityUser_0000.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityUser_0000.dir/build
.PHONY : libinfinityUser_0000/fast

#=============================================================================
# Target rules for targets named libinfinityKernel_0001

# Build rule for target.
libinfinityKernel_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityKernel_0001
.PHONY : libinfinityKernel_0001

# fast build rule for target.
libinfinityKernel_0001/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityKernel_0001.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityKernel_0001.dir/build
.PHONY : libinfinityKernel_0001/fast

#=============================================================================
# Target rules for targets named libinfinityKernel_0002

# Build rule for target.
libinfinityKernel_0002: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityKernel_0002
.PHONY : libinfinityKernel_0002

# fast build rule for target.
libinfinityKernel_0002/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityKernel_0002.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityKernel_0002.dir/build
.PHONY : libinfinityKernel_0002/fast

#=============================================================================
# Target rules for targets named libinfinityUser_0001

# Build rule for target.
libinfinityUser_0001: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityUser_0001
.PHONY : libinfinityUser_0001

# fast build rule for target.
libinfinityUser_0001/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityUser_0001.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityUser_0001.dir/build
.PHONY : libinfinityUser_0001/fast

#=============================================================================
# Target rules for targets named libinfinityUser_0003

# Build rule for target.
libinfinityUser_0003: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityUser_0003
.PHONY : libinfinityUser_0003

# fast build rule for target.
libinfinityUser_0003/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityUser_0003.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityUser_0003.dir/build
.PHONY : libinfinityUser_0003/fast

#=============================================================================
# Target rules for targets named libinfinityKernel_0003

# Build rule for target.
libinfinityKernel_0003: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityKernel_0003
.PHONY : libinfinityKernel_0003

# fast build rule for target.
libinfinityKernel_0003/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityKernel_0003.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityKernel_0003.dir/build
.PHONY : libinfinityKernel_0003/fast

#=============================================================================
# Target rules for targets named libinfinityKernel

# Build rule for target.
libinfinityKernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityKernel
.PHONY : libinfinityKernel

# fast build rule for target.
libinfinityKernel/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityKernel.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityKernel.dir/build
.PHONY : libinfinityKernel/fast

#=============================================================================
# Target rules for targets named libinfinityUser_0002

# Build rule for target.
libinfinityUser_0002: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityUser_0002
.PHONY : libinfinityUser_0002

# fast build rule for target.
libinfinityUser_0002/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityUser_0002.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityUser_0002.dir/build
.PHONY : libinfinityUser_0002/fast

#=============================================================================
# Target rules for targets named libinfinityKernel_0000

# Build rule for target.
libinfinityKernel_0000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityKernel_0000
.PHONY : libinfinityKernel_0000

# fast build rule for target.
libinfinityKernel_0000/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityKernel_0000.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityKernel_0000.dir/build
.PHONY : libinfinityKernel_0000/fast

#=============================================================================
# Target rules for targets named libinfinityUser

# Build rule for target.
libinfinityUser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinfinityUser
.PHONY : libinfinityUser

# fast build rule for target.
libinfinityUser/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/libinfinityUser.dir/build.make firmware/infinityctrl/CMakeFiles/libinfinityUser.dir/build
.PHONY : libinfinityUser/fast

#=============================================================================
# Target rules for targets named infinityctrl

# Build rule for target.
infinityctrl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infinityctrl
.PHONY : infinityctrl

# fast build rule for target.
infinityctrl/fast:
	$(MAKE) -f firmware/infinityctrl/CMakeFiles/infinityctrl.dir/build.make firmware/infinityctrl/CMakeFiles/infinityctrl.dir/build
.PHONY : infinityctrl/fast

#=============================================================================
# Target rules for targets named rebootex

# Build rule for target.
rebootex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rebootex
.PHONY : rebootex

# fast build rule for target.
rebootex/fast:
	$(MAKE) -f firmware/rebootex/CMakeFiles/rebootex.dir/build.make firmware/rebootex/CMakeFiles/rebootex.dir/build
.PHONY : rebootex/fast

#=============================================================================
# Target rules for targets named mecompat

# Build rule for target.
mecompat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mecompat
.PHONY : mecompat

# fast build rule for target.
mecompat/fast:
	$(MAKE) -f firmware/mecompat/CMakeFiles/mecompat.dir/build.make firmware/mecompat/CMakeFiles/mecompat.dir/build
.PHONY : mecompat/fast

#=============================================================================
# Target rules for targets named procompat

# Build rule for target.
procompat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 procompat
.PHONY : procompat

# fast build rule for target.
procompat/fast:
	$(MAKE) -f firmware/procompat/CMakeFiles/procompat.dir/build.make firmware/procompat/CMakeFiles/procompat.dir/build
.PHONY : procompat/fast

#=============================================================================
# Target rules for targets named arkcompat

# Build rule for target.
arkcompat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arkcompat
.PHONY : arkcompat

# fast build rule for target.
arkcompat/fast:
	$(MAKE) -f firmware/arkcompat/CMakeFiles/arkcompat.dir/build.make firmware/arkcompat/CMakeFiles/arkcompat.dir/build
.PHONY : arkcompat/fast

#=============================================================================
# Target rules for targets named bootloader661

# Build rule for target.
bootloader661: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootloader661
.PHONY : bootloader661

# fast build rule for target.
bootloader661/fast:
	$(MAKE) -f firmware/bootloader/CMakeFiles/bootloader661.dir/build.make firmware/bootloader/CMakeFiles/bootloader661.dir/build
.PHONY : bootloader661/fast

#=============================================================================
# Target rules for targets named bootloader660

# Build rule for target.
bootloader660: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootloader660
.PHONY : bootloader660

# fast build rule for target.
bootloader660/fast:
	$(MAKE) -f firmware/bootloader/CMakeFiles/bootloader660.dir/build.make firmware/bootloader/CMakeFiles/bootloader660.dir/build
.PHONY : bootloader660/fast

#=============================================================================
# Target rules for targets named recovery

# Build rule for target.
recovery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recovery
.PHONY : recovery

# fast build rule for target.
recovery/fast:
	$(MAKE) -f firmware/recovery/CMakeFiles/recovery.dir/build.make firmware/recovery/CMakeFiles/recovery.dir/build
.PHONY : recovery/fast

#=============================================================================
# Target rules for targets named configuration

# Build rule for target.
configuration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 configuration
.PHONY : configuration

# fast build rule for target.
configuration/fast:
	$(MAKE) -f app/CMakeFiles/configuration.dir/build.make app/CMakeFiles/configuration.dir/build
.PHONY : configuration/fast

#=============================================================================
# Target rules for targets named intrafont

# Build rule for target.
intrafont: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrafont
.PHONY : intrafont

# fast build rule for target.
intrafont/fast:
	$(MAKE) -f app/3rdparty/intraFont-G/CMakeFiles/intrafont.dir/build.make app/3rdparty/intraFont-G/CMakeFiles/intrafont.dir/build
.PHONY : intrafont/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... bin2cpp"
	@echo "... hashgen"
	@echo "... psppack"
	@echo "... pack_user_fw_module"
	@echo "... pack_kernel_module"
	@echo "... pack_updater"
	@echo "... power"
	@echo "... scePower_0002"
	@echo "... scePower_0001"
	@echo "... scePower_0000"
	@echo "... syscon"
	@echo "... sceSyscon_driver_0001"
	@echo "... sceSyscon_driver_0000"
	@echo "... vshbridge"
	@echo "... sceVshBridge_0001"
	@echo "... sceVshBridge_0000"
	@echo "... netifhandle"
	@echo "... sceNetIfhandle_lib_0001"
	@echo "... sceNetIfhandle_lib_0000"
	@echo "... memlmd"
	@echo "... semaphore_0001"
	@echo "... semaphore_0000"
	@echo "... modulemgr"
	@echo "... ModuleMgrForUser_0001"
	@echo "... ModuleMgrForUser_0000"
	@echo "... kexploit"
	@echo "... kernel_helper"
	@echo "... kernel_helper_user_0000"
	@echo "... kernel_helper_user"
	@echo "... kernel_helper_user_0001"
	@echo "... kernel_helper_user_0003"
	@echo "... kernel_helper_user_0002"
	@echo "... kernel_helper_user_0004"
	@echo "... libconfig_kernel_0002"
	@echo "... libconfig_kernel_0003"
	@echo "... libconfig_user_0003"
	@echo "... libconfig_kernel_0007"
	@echo "... libconfig"
	@echo "... libconfig_user_0000"
	@echo "... libconfig_user_0004"
	@echo "... libconfig_kernel_0005"
	@echo "... libconfig_user_0011"
	@echo "... libconfig_user_0012"
	@echo "... libconfig_kernel_0000"
	@echo "... libconfig_kernel_0009"
	@echo "... libconfig_static"
	@echo "... libconfig_kernel_0011"
	@echo "... libconfig_kernel_0001"
	@echo "... libconfig_kernel_0012"
	@echo "... libconfig_kernel_0006"
	@echo "... libconfig_user_0001"
	@echo "... libconfig_user_0005"
	@echo "... libconfig_kernel_0004"
	@echo "... libconfig_user_0002"
	@echo "... libconfig_user_0007"
	@echo "... libconfig_user_0009"
	@echo "... libconfig_kernel_0008"
	@echo "... libconfig_user_0008"
	@echo "... libconfig_kernel_0010"
	@echo "... libconfig_user_0006"
	@echo "... libconfig_user_0010"
	@echo "... libconfig_user"
	@echo "... libconfig_kernel"
	@echo "... reboot"
	@echo "... infinityboot"
	@echo "... libinfinityUser_0000"
	@echo "... libinfinityKernel_0001"
	@echo "... libinfinityKernel_0002"
	@echo "... libinfinityUser_0001"
	@echo "... libinfinityUser_0003"
	@echo "... libinfinityKernel_0003"
	@echo "... libinfinityKernel"
	@echo "... libinfinityUser_0002"
	@echo "... libinfinityKernel_0000"
	@echo "... libinfinityUser"
	@echo "... infinityctrl"
	@echo "... rebootex"
	@echo "... mecompat"
	@echo "... procompat"
	@echo "... arkcompat"
	@echo "... bootloader661"
	@echo "... bootloader660"
	@echo "... recovery"
	@echo "... configuration"
	@echo "... intrafont"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

